### ISSUE TITLE
can't use crypto prices?

### ISSUE THREAD

**Issue by avimar** [Stanford-Mobisocial-IoT-Lab/almond-cloud#35]
>price of btc
QUOTE: Look back over the past, with its changing empires that rose and fell, and you can foresee the future, too. By Marcus Aurelius .

>get price of btc
You don't have a Uber

Do I nee to enable it or something for my account?

**Comment by rayslxu** [comment]
Thank you for using Almond. 

You don't need to enable public services to use them.
We trained our natural language model with the cryptocurrency name instead of the code, so it may not be able to recognize "btc". You can try "price of bitcoin" instead.
